spring:
  application:
    name: at-dssb

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/at_dssb}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/dev/protocol/openid-connect/certs}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
