name: ${COMPOSE_PROJECT_NAME:-at_dssb_stack}

services:
  mongo:
    image: mongo:7
    container_name: ${COMPOSE_PROJECT_NAME:-at_dssb_stack}_mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-at_dssb}
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  mongo-express:
    image: mongo-express:1
    container_name: ${COMPOSE_PROJECT_NAME:-at_dssb_stack}_mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "${MONGO_EXPRESS_PORT:-8082}:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-admin}

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: ${COMPOSE_PROJECT_NAME:-at_dssb_stack}_keycloak
    restart: unless-stopped
    command: ["start-dev", "--http-port=8081", "--import-realm"]
    ports:
      - "${KEYCLOAK_PORT:-8081}:8081"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro

volumes:
  mongo_data:
  keycloak_data:
